
NAME = "nayutaya-ironnews-utility"

task :default => :gemspec

task :version do
  require "lib/ironnews_utility/version"
  cur_version  = IronnewsUtility::VERSION
  next_version = cur_version.succ
  puts("#{cur_version} -> #{next_version}")

  filename = File.join(File.dirname(__FILE__), "lib", "ironnews_utility", "version.rb")
  File.open(filename, "wb") { |file|
    file.puts
    file.puts(%|module IronnewsUtility|)
    file.puts(%|  VERSION = "#{next_version}"|)
    file.puts(%|end|)
  }
end

desc "generate gemspec file from template"
task :gemspec do
  require "erb"
  require "lib/ironnews_utility"

  src  = File.open("#{NAME}.gemspec.erb", "rb") { |file| file.read }
  erb  = ERB.new(src, nil, "-")

  version = IronnewsUtility::VERSION
  date    = Time.now.strftime("%Y-%m-%d")

  files      = Dir.glob("**/*").select { |s| File.file?(s) }.reject { |s| /\.gem\z/ =~ s }
  test_files = Dir.glob("test/**").select { |s| File.file?(s) }

  File.open("#{NAME}.gemspec", "wb") { |file|
    file.write(erb.result(binding))
  }
end

desc "build gem"
task :build do
  sh "gem build #{NAME}.gemspec"
end

task :push do
  require "lib/ironnews_utility"
  target = "#{NAME}-#{IronnewsUtility::VERSION}.gem"
  sh "gem push #{target}"
end
