
task :default => :gemspec

desc "generate gemspec file from template"
task :gemspec do
  require "erb"
  require "lib/bookmark_utility"

  name = "nayutaya-bookmark-utility"
  src  = File.open("#{name}.gemspec.erb", "rb") { |file| file.read }
  erb  = ERB.new(src, nil, "-")

  version = BookmarkUtility::VERSION
  date    = Time.now.strftime("%Y-%m-%d")

  files      = Dir.glob("**/*").select { |s| File.file?(s) }
  test_files = Dir.glob("test/**").select { |s| File.file?(s) }

  File.open("#{name}.gemspec", "wb") { |file|
    file.write(erb.result(binding))
  }
end
